"""Created user and post tables

Revision ID: 9dad57699504
Revises: 
Create Date: 2023-11-25 01:42:28.557098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dad57699504'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
    op.alter_column('user', 'image_file',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'image_file',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_table('post')
    # ### end Alembic commands ###
