"""Add recipe_id column to shopping_list table

Revision ID: 04c2180d1f93
Revises: a3869a6d8db8
Create Date: 2023-12-03 17:58:42.959411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c2180d1f93'
down_revision = 'a3869a6d8db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.alter_column('ingredient',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.alter_column('ingredient',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
