"""Add ShoppingList table columns

Revision ID: a3869a6d8db8
Revises: f91d67c49d8e
Create Date: 2023-12-03 17:29:30.659768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3869a6d8db8'
down_revision = 'f91d67c49d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ingredient', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.drop_column('ingredient')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
